theme: jekyll-theme-slate
title:  Human-Centered Robotics Lab
description: The Human-Centered Robotics lab is part of the Penn State University Mechanical Engineering Department. Our research focuses on computational methods in human-machine interaction,robot learning from demonstration, and haptics.
markdown: kramdown

# baseurl: /psu-hcr.github.io
